// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTFVj9MVq7KoJIBxofM1X0oSBb24qTMMI',
    appId: '1:1095690596356:web:f708709211b579cc9d8551',
    messagingSenderId: '1095690596356',
    projectId: 'attandancemanagementsyst-17486',
    authDomain: 'attandancemanagementsyst-17486.firebaseapp.com',
    storageBucket: 'attandancemanagementsyst-17486.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAApn3pNA-eFLWz7R2Hy0jutPEQobgyMCs',
    appId: '1:1095690596356:android:e4051c0d8150c05c9d8551',
    messagingSenderId: '1095690596356',
    projectId: 'attandancemanagementsyst-17486',
    storageBucket: 'attandancemanagementsyst-17486.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnH-uPtIUAUpwuIZ9KY--9cLUlvYEqMog',
    appId: '1:1095690596356:ios:fd5e7ae11ee0c57c9d8551',
    messagingSenderId: '1095690596356',
    projectId: 'attandancemanagementsyst-17486',
    storageBucket: 'attandancemanagementsyst-17486.appspot.com',
    iosClientId: '1095690596356-ush46ugiba61ch2o7hclt7sudeq0tkpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnH-uPtIUAUpwuIZ9KY--9cLUlvYEqMog',
    appId: '1:1095690596356:ios:fd5e7ae11ee0c57c9d8551',
    messagingSenderId: '1095690596356',
    projectId: 'attandancemanagementsyst-17486',
    storageBucket: 'attandancemanagementsyst-17486.appspot.com',
    iosClientId: '1095690596356-ush46ugiba61ch2o7hclt7sudeq0tkpd.apps.googleusercontent.com',
    iosBundleId: 'com.example.ams',
  );
}
